env:
  global:
    - ARTIFACTS_AWS_REGION=us-east-1
    - ARTIFACTS_S3_BUCKET=pebb
    - secure: YOLiy0c68X43MSrxlEsz2r3guZy/7D2MwpJaffPCN8Lrp8zgrVi8EU320mkn9QfK7WxSjXz996XcCIjQQCMb9HgrWEOQkZBCIJ1ABm87GLqDC9XLFgt7YrLl3chlli9PIRmt42eYTqiEeZt1nXwkgUMZ4VVHzZbCGR3g207cKlc=
    - secure: NT3j9ng3lW+Cpc5BZIcnIERF1d5fHlKRIhPzMqH32eVXc5YgdnPoX46EtAVFvzRyEIHzgDKrkXvhHhnf4CUNVP5RBKRK9i88PQahY3EgyFe33785LvK4BD4qGD6LqZa1ZfQsQppGHFP5WrRFxy2pJKFsMCTn9KMFRN2B5mGoFg8=

before_script:
  - gem install travis-artifacts
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - python -m unittest testfoo
  - echo baz bar > bazbar.txt
  - cat bazbar.txt

after_script:
#  - travis-artifacts upload --path hello.txt --target-path .
  - travis-artifacts upload --path bazbar.txt 
  - echo https://s3.amazonaws.com/pebb/artifacts/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/hello.txt
